### ISSUE TITLE
为什么要把orm替换成ent呢？

### ISSUE THREAD

**Issue by caik13** [Sloaix/Gofi#16]
了解了一下ent，写起来确实特方便；
但是为什么要换呢？

ent的表有 edge的时候，把主表和edge的数据一起查询回来的数据格式有点难受，
他是在主表增加了个 edge字段，然后把关联表的数据都放到了edge下面。

**Comment by Sloaix** [comment]
已放弃ent方案,feat_ent分支有做尝试。
