### ISSUE TITLE
能否加个搜索文件名的功能？

### ISSUE THREAD

**Issue by lhmwzy** [Sloaix/Gofi#19]
如标题

**Comment by Sloaix** [comment]
Angular重构版本已经开始开发搜索功能的，不过对于功能的细节还需要再细化一下。

**搜索feature**
- 根据关键字过滤出当前文件夹下的指定文件
- 根据关键字过滤出当前文件下的指定文件，包括子文件夹
- 根据关键字进行全仓搜索

**Comment by Sloaix** [comment]
![1](https://user-images.githubusercontent.com/2627625/87796302-c7646700-c87b-11ea-969f-a4574d920d55.png)

**Comment by Sloaix** [comment]
鉴于angular版本的已经被我放弃了，所以上述feature暂时还未实现。。。

由于Gofi并没有对文件系统进行索引，所以在没有索引的情况下，只能简单的遍历当前目录下所有文件，进行搜索。说是搜索不如说是简单的过滤，这样的效率实在太低。

这次重构的时候我好好的思考了一下，如果要上搜索的feature，还是需要对文件进行索引，这是必须的，不然体验会很差。

**Comment by Sloaix** [comment]
discuss in #27
