### ISSUE TITLE
excel word等办公文件在线预览编辑

### ISSUE THREAD

**Issue by Avey777** [Sloaix/Gofi#20]
可以集成一个office文档在线预览编辑的功能吗？

**Comment by Avey777** [comment]
蓝眼云盘：https://blog.eyeblue.cn/home/article/8953d493-f80a-4be0-bde2-50d3c5747430
目前也是部署比较简单的

**Comment by Sloaix** [comment]
暂时没有该计划。目前的主要计划是Angular重构，达到之前的feature水准，下一步会进行搜索feature开发，接着是bonjour-局域网设备发现协议尝试。
