### ISSUE TITLE
what's the default username/password ?

### ISSUE THREAD

**Issue by changchichung** [Sloaix/Gofi#29]
I can't get into the setting session since I don't know what's the default username/password .
I can't find that info in any page/documents.

**Comment by Sloaix** [comment]
my mistake

https://github.com/Sloaix/Gofi/blob/master/gofi-backend/db/user.go#L10-L13
```go
const (
	AdminUsername = "admin"
	AdminPassword = "password"
)
```

**Comment by Sloaix** [comment]
My focus recently shifted to entrepreneurship, and I was surprised to see new users on Gofi.
