### ISSUE TITLE
docker安装后无法打开页面

### ISSUE THREAD

**Issue by Enoliu** [Sloaix/Gofi#31]
http://172.17.0.3:8080/api/configuration  请求这个地址，但这个ip明显是docker内部的地址啊，浏览器里面肯定打不开啊

![image](https://user-images.githubusercontent.com/25947382/144025299-c71e2bd1-abab-4c64-a9ae-d054f0cf1d65.png)

**Comment by Sloaix** [comment]
用nightly-prod-latest这个镜象，现在的latest还不是最新版本。：
```bash
docker run -d \
              --name=gofi \
              -p 80:8080 \
              -v ~/gofi:/app \
              -v ~/gofi/storage:/app/storage \
              --restart unless-stopped \
              sloaix/gofi:nightly-prod-latest
```
