### ISSUE TITLE
ubuntu 18.04 搭建失败

### ISSUE THREAD

**Issue by deplives** [Sloaix/Gofi#5]
本地Ubuntu18.04 build 成功，启动之后 打开页面提示一个 undefined 错误，页面空白

**Comment by Sloaix** [comment]
你需要设置一下ip

**Comment by Sloaix** [comment]
gofi -ip <服务器的局域网ip地址>

**Comment by Sloaix** [comment]
下个版本，会从所有本地ip从拿去属于
"192.168.0.0/16",
 "172.16.0.0/12", 
"10.0.0.0/8"
这几个网段的ip作为前端请求的ip。

如果本机的ip不属于以上任意网段，默认使用127.0.0.1作为ip地址。

没有问题我就关闭issue了，有问题再打开。
