### ISSUE TITLE
MacOS、Linux下都运行不起来，具体如图

### ISSUE THREAD

**Issue by li-xunhuan** [Sloaix/Gofi#6]
<img width="419" alt="QQ20191220-145442@2x" src="https://user-images.githubusercontent.com/10476982/71236057-e841f980-2338-11ea-96c0-58da417ca30f.png">

**Comment by Sloaix** [comment]
本地编译没有问题。初步定为是upx的锅。

**Comment by Sloaix** [comment]
v0.5.3我已经重新再本地编译了这个版本了，已经重新上传了一遍二进制包，后面我会把GithubActions的upx暂时移除。

**Comment by Sloaix** [comment]
点击这里下载:[v0.5.3 Release](https://github.com/Sloaix/Gofi/releases/tag/v0.5.3)
