### ISSUE TITLE
如何默认关闭上传？

### ISSUE THREAD

**Issue by ferocknew** [Sloaix/Gofi#7]
如题

**Comment by Sloaix** [comment]
目前没有权限，要等权限加上后才能做。

**Comment by ferocknew** [comment]
> 目前没有权限，要等权限加上后才能做。

是否考虑，配置db 里增加一个参数。这似乎是现在成本最低的实现方式。

**Comment by Sloaix** [comment]
> > 目前没有权限，要等权限加上后才能做。
> 
> 是否考虑，配置db 里增加一个参数。这似乎是现在成本最低的实现方式。

参数可以加，但是没有意义。目前只要能访问Gofi的人，就有修改配置的权限。预览网站之所以不能修改配置，是因为我编译的是Preview包，代码对Preview包做了区别处理。

**Comment by Sloaix** [comment]
Sprint2已经结束了，Sprint3里面会新增权限这部分的能力。
